# Generated by Django 6.0.7 on 2026-07-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('user', 'User'), ('repo', 'Repository')], max_length=10)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('item_id', 'provider', 'item_type')},
            },
        ),
    ]
