# Generated by assistant - add star_count to SavedItem
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="saveditem",
            name="star_count",
            field=models.IntegerField(default=0),
            preserve_default=True,
        ),
    ]
